@startuml
'https://plantuml.com/use-case-diagram
object Nurse
object Vaccine{
-dosage
-brand
-age range
-vaccine interval
}
object SNSuser{
-SNS user number
-phone number
-e-mail address
-health conditions
}
object VaccineAdministration
object Employees

Vaccine"1" -- "1"Nurse: > administered by
Vaccine"1" -- "*"VaccineAdministration: < of
Employees"1"--"1" Nurse: > plays as
VaccineAdministration"*" -- "1"SNSuser: > administered on


@enduml