@startuml
'https://plantuml.com/sequence-diagram

autonumber

autonumber
actor "Nurse" as nurse

activate nurse
nurse-> "System:" : selects vaccination center where she is working
activate "System:"
"System:" --> nurse : shows menu with this role's possible operations
nurse-> "System:" : asks to consult the users in the waiting room
"System:" --> nurse : shows users in the waiting room per order of arrival
deactivate "System:"
@enduml