@startuml
'https://plantuml.com/object-diagram

object SNSuser
object DGS
object Administrator
object Coordinator
object Nurse
object Recepionist
object HealthCareCenter
object VaccineBrand
object TypeVaccine
object Vaccine
object VaccineSchedule
object StatisticalDataVaccination
object CertificateVaccination
object VaccineAdministration
object Confirmation
object SmsConfirmation
object EmailConfirmation
object Employee

SNSuser"*"--"1" DGS : < owns
DGS"1" -- "*"Coordinator : > owns
DGS "1"--"1" Vaccine : > applies
Employee"1"--"1" Recepionist: > plays as
Employee"1"--"1" Nurse: > plays as
Employee"1"--"1" Coordinator: > plays as
Employee"1"--"1" Administrator: > plays as
TypeVaccine "1"--"*"VaccineBrand : < is of
SNSuser "1"--"*" CertificateVaccination: < requested by
Coordinator"1" --"1" HealthCareCenter: > manages
HealthCareCenter "1"--"*" Nurse: < part of
HealthCareCenter "1"--"*" Recepionist: < part of
Nurse "1"--"*" VaccineBrand: > checks
Coordinator -- StatisticalDataVaccination
HealthCareCenter "*"--"*" VaccineBrand: > can administer
VaccineSchedule"*" -- "1"SNSuser: > created for
VaccineSchedule"*" -- "1"Recepionist: > created for
VaccineSchedule"*" -- "*"TypeVaccine:> for taking
Vaccine"1" -- "1"Nurse: > administered by
Vaccine"1" -- "*"VaccineAdministration: < of
Vaccine"1" --"1" VaccineBrand:> is of
Recepionist"1" -- "*"SNSuser: < registered by
VaccineAdministration"*" -- "1"SNSuser: > administer on
VaccineAdministration"1" -- "1"VaccineSchedule: < fulfilling
CertificateVaccination"*" -- "1"Nurse: < issued by
Confirmation"1" -- "1"VaccineSchedule: < emits
Confirmation"1" -- "1"SmsConfirmation:> sends
Confirmation "1"--"1" EmailConfirmation: > sends



@enduml
