@startuml
autonumber
actor "Administrator" as adm

activate adm
adm -> ":System" : asks to specify a new vaccine type
activate ":System"
":System" --> adm : requests data (disease)
deactivate ":System"

adm -> ":System" : types requested data

@enduml