@startuml

object DGS
object Employees
object Administrator
object Vaccine{
-dosage
-doses
-brand
-age range
-vaccine interval

}
object VaccineAdministration
object TypeVaccine{
-disease
}


DGS"1" -- "*"Employees : > owns
DGS "1"--"1" Vaccine : > applies
Vaccine"1" --"1" TypeVaccine:> is of
Vaccine"1" -- "*"VaccineAdministration: < of
Employees"1"--"1" Administrator: > plays as

@enduml