@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

Class Company{
-List<SNSuser> SNSuserList
-designation
    +createSNSuser(dtoSNSuser dto)
    +validateSNSuser(SNSuser user)
    -validateSNSuserDTO(dtoSNSuser dto)
    +saveSNSuser(dtoSNSuser dto)
    +printSNSuser(SNSuser user)
}
Class AuthFacade{
+addUserWithRole(String name, String email, String pwd, String roleId)
}

Class App{
+getIntance()
+getIntance.getCompany()
}

Class SNSuser{
-String sex
-LocalDate birth
-Int SNSnumber
}

Class User{
-String name
-String residenceAddress
-String email
-int phoneNumber
-int ccNumber
}

Class AddSNSfromCSVUI{
+run()
-file()
-copyDataFromFile
-validateContents(String[] Line)
}
Class AddSNSfromCSVController{
+createSNSuser(dtoSNSuser dto)
+saveSNSuser(dtoSNSuser dto)
+printSNSuser()
}

AddSNSfromCSVUI..>AddSNSfromCSVController
AddSNSfromCSVController..>Company
AddSNSfromCSVController..>App
Company"1"-->"*"User:owns
Company..>AuthFacade
User"*"-->"1"SNSuser:is a


@enduml