@startuml
'https://plantuml.com/class-diagram
left to right direction

object SNSuser{
-name
-address
-SNS user number
-phone number
-e-mail address
-health conditions
}
object Administrator

Administrator"1" -- "*" SNSuser: > manages/registers


@enduml