@startuml
'https://plantuml.com/class-diagram


object SNSuser{
-name
-address
-SNS user number
-phone number
-e-mail address
-health conditions
}
object Administrator

Administrator"*" -- "*" SNSuser: > manages/registers


@enduml