@startuml
'https://plantuml.com/sequence-diagram

    participant ":RegisterVaccineAdministrationController" as  CTRL
    participant "adminstration\n:VaccinationAdministrationRecord" as record
    participant ":Vaccine" as vaccine


autonumber
->CTRL:createVaccinationAdminstration(lotNumber)
activate CTRL
create record
CTRL->record:VaccinationAdminstrationRecord(SNSuserNumber, vaccine, dose, lotNumber, NurseAdministrationDateTime)


@enduml