@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

package UI{
    package GUI{
    Class RegisterVaccineAdministrationUI{
    -MainScene mainScene
    -NurseUI nurseUI
    -Stage popUpWindow

    +getMainScene()
    +getController()
    +returnNurseUI()
    +toVaccineAdministrationScene1()
    +toVaccineAdministrationScene2()
    +toVaccineAdministrationScene2FreshController()
    +toVaccineAdministrationScene3()
    +toVaccineAdministrationScene4()
    +closePopUp()
    -replacePopUp(fxml)
    }
    }
}

package core{
    package controller{

Class RecordVaccineAdministrationController{

- App app

+clear()
+createVaccinationAdminstration(int recoryTime,String lotNumber)
+saveVaccinationAdminstration()
+getVaccinationFacilities()
+setVaccinationFacility(index)
+checkIfWaitingListEmpty()
+getWaitingList()
+getAppoimentInfo()
+getVaccineInfo()
+getVaccineList()
+setVaccine(int index)
+getUserVaccineCard()
-getVaccinationAppointment()
-createVaccineCard()
-updateVaccineCard()
+validateVaccineAdministration()
+ sendSMS(minutes)
-deleteAppoiment()
-save()
}
}
package domain{
Class Company{
-List<VaccinationFacility> vaccinationFacilityList
-List<Vaccine> vaccineList


+getVaccinationFacilityList()
+getVaccinationFacilityFromList(index)
+getVaccineListByVaccineType(typeVaccine)
+saveVaccinationFacilityListFile();
+saveSNSusersListFile();
}

Class SNSuser{
-String name
-String residenceAddress
-String email
-int phoneNumber
-int ccNumber
-String sex
-LocalDate birth
-int SNSnumber
-String password

+getVaccineCards()
+getName()
+getAge()
+getSNSnumber()
+updateVaccinationRecord(vaccine,administraitonTime)
}

Class VaccinationFacility{
-String name
-String address
-int phoneNumber
-String emailAddress
-int faxNumber
-String websiteAddress
-LocalTime openingHours
-LocalTime closingHours
-int slotDuration
-int maximumNumberOfVaccinesPerSlot
-List<Arrival> waitingList

+getWaitingList()
+getVaccinationScheduleList()
+addVaccinationAdminstrationRecord(record)
}


Class VaccineCard{
-LocalDateTime date
-int numberDosesTaken

+checkTypeVaccine(typeVaccine)
}

Class VaccinationAdministrationRecord{
-int SNSuserNumber
-String lotNumber
-LocalDateTime ScheduledDateTime
-LocalDateTime NurseAdministrationDateTime
-LocalDateTime LeavingDateTime
}

Class Vaccine{

-String name

+getName()
+getAgeGroup(age)
+getVaccineAdministration()
}

Class VaccineAdministration{
- String brand;
- List<Integer> minAge;
-List<Integer> maxAge;
-List<Integer> dosage;
-List<Integer> doses;
-ArrayList<ArrayList<Integer>> vaccineInterval;
}

Class TypeVaccine{
-String name;
-String description;
-String code;
-String technology;
}

Class Arrival{
-SNSuser snSuser
-LocalDateTime timeOfArrival

+getSnSuser()
}

Class SendSMSTask{
-setMessage();
}
}
}
Interface TimerTask{
+run()
}


RegisterVaccineAdministrationUI..> RecordVaccineAdministrationController

RecordVaccineAdministrationController ..>Company
RecordVaccineAdministrationController ..>VaccinationFacility
RecordVaccineAdministrationController ..>SNSuser
RecordVaccineAdministrationController ..>VaccinationAdministrationRecord
RecordVaccineAdministrationController ..>Vaccine
RecordVaccineAdministrationController ..>SendSMSTask

Company"1" -->"*"SNSuser:"owns"
SNSuser"1" -->"*"VaccineCard:"has"
VaccineCard"*"-->"1"Vaccine:"has"
Vaccine"1" -->"*"VaccineAdministration:"has"
VaccinationFacility"1"-->"*"VaccinationAdministrationRecord:"has"
VaccinationFacility"1"-->"*"Arrival:"has"
Vaccine"1"-->"*"TypeVaccine:"has"

SendSMSTask..|>TimerTask
@enduml