@startuml
left to right direction

package DGSStaff {
  actor Receptionist
  actor Nurse
  actor CenterCoordinator
  actor Administrator

}
package Other {
actor SNSUser
}

rectangle System {


        SNSUser -- (UC01: Schedule Vaccination)
        Receptionist -- (UC04: Register the arrival of the patient on the system)
        Nurse -- (UC05: Consult the users in the waiting room of a vaccination center. )
        Nurse -- (UC08: Record the administration of vaccine to an SNS user.\nReceive an SMS/EMAIL notification that the recovery period is over)
        Administrator -- (UC09: Register a vaccination center to respond a certain pandemic)
        Administrator -- (UC10: Register an Employee)
        Administrator -- (UC11: Get a list of Employees with a given function/role)
        Administrator -- (UC13: Specify a new vaccine and its administration)
        Administrator -- (UC14: Load a set of users from a CSV file)
        CenterCoordinator -- (UC15: Check and export vaccination statistics to csv file, the total number of fully vaccinated user per day.)
        CenterCoordinator-- (UC16: Analyze the performance of a center.)
        CenterCoordinator -- (UC17: Import data from a legacy system that was used in the past to manage centers.)


   }
@enduml