@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

Class Company{
-designation
}
Class Employee{
-id
-name
-address
-phoneNumber
-email
-ccNumber
}
Class User{
-id
-password
}
Class OrganizationRole{
-description
}

Company"1"--"*"Employee:employ >
Employee"0.1"--"1"User:relates to >
Company"1"--"*"OrganizationRole: comprehends >
Employee"*"--"1"OrganizationRole:has/plays >


@enduml